// AUTOGENERATED FILE -- DO NOT EDIT DIRECTLY
declare namespace ExportsModuleScssNamespace {
  export interface IExportsModuleScss {
    anchor: string;
    heading: string;
    linkIconSize: string;
    path: string;
    svg: string;
  }
}

declare const ExportsModuleScssModule: ExportsModuleScssNamespace.IExportsModuleScss;

export = ExportsModuleScssModule;
