// AUTOGENERATED FILE -- DO NOT EDIT DIRECTLY

declare namespace StylesModuleScssNamespace {
  export interface IStylesModuleScss {
    active: string;
    heading: string;
    hidden: string;
    items: string;
    left: string;
    link: string;
    logo: string;
    nav: string;
    navItem: string;
    navbar: string;
    right: string;
    toc: string;
    tocContainer: string;
  }
}

declare const StylesModuleScssModule: StylesModuleScssNamespace.IStylesModuleScss;

export = StylesModuleScssModule;
