// AUTOGENERATED FILE -- DO NOT EDIT DIRECTLY

declare namespace StylesModuleScssNamespace {
  export interface IStylesModuleScss {
    codeBlock: string;
    codeBlockContainer: string;
    content: string;
    copied: string;
    copyButton: string;
    copyIcon: string;
    icons: string;
    line: string;
    lineContent: string;
    lineNumber: string;
    lines: string;
    numbered: string;
    standalone: string;
    successIcon: string;
    title: string;
  }
}

declare const StylesModuleScssModule: StylesModuleScssNamespace.IStylesModuleScss;

export = StylesModuleScssModule;
