// AUTOGENERATED FILE -- DO NOT EDIT DIRECTLY
declare namespace StylesModuleScssNamespace {
  export interface IStylesModuleScss {
    active: string;
    heading: string;
    items: string;
    link: string;
    nav: string;
    toc: string;
  }
}

declare const StylesModuleScssModule: StylesModuleScssNamespace.IStylesModuleScss;

export = StylesModuleScssModule;
