// AUTOGENERATED FILE -- DO NOT EDIT DIRECTLY
declare namespace MarkdownModuleScssNamespace {
  export interface IMarkdownModuleScss {
    content: string;
    hidden: string;
    left: string;
    logo: string;
    markdown: string;
    navItem: string;
    navbar: string;
    right: string;
  }
}

declare const MarkdownModuleScssModule: MarkdownModuleScssNamespace.IMarkdownModuleScss;

export = MarkdownModuleScssModule;
