// AUTOGENERATED FILE -- DO NOT EDIT DIRECTLY
declare namespace MarkdownModuleScssNamespace {
  export interface IMarkdownModuleScss {
    content: string;
    markdown: string;
  }
}

declare const MarkdownModuleScssModule: MarkdownModuleScssNamespace.IMarkdownModuleScss;

export = MarkdownModuleScssModule;
