// AUTOGENERATED FILE -- DO NOT EDIT DIRECTLY
declare namespace ExportsModuleScssNamespace {
  export interface IExportsModuleScss {
    iconSize: string;
  }
}

declare const ExportsModuleScssModule: ExportsModuleScssNamespace.IExportsModuleScss;

export = ExportsModuleScssModule;
