// AUTOGENERATED FILE -- DO NOT EDIT DIRECTLY

declare namespace StylesModuleScssNamespace {
  export interface IStylesModuleScss {
    active: string;
    arrow: string;
    category: string;
    collapsed: string;
    contentContainer: string;
    contentWrapper: string;
    desktop: string;
    hidden: string;
    items: string;
    left: string;
    link: string;
    logo: string;
    navItem: string;
    navbar: string;
    right: string;
    sidebarContainer: string;
    wrapper: string;
  }
}

declare const StylesModuleScssModule: StylesModuleScssNamespace.IStylesModuleScss;

export = StylesModuleScssModule;
