// AUTOGENERATED FILE -- DO NOT EDIT DIRECTLY

declare namespace StylesExportModuleScssNamespace {
  export interface IStylesExportModuleScss {
    hidden: string;
    left: string;
    logo: string;
    navItem: string;
    navbar: string;
    navbarHeight: string;
    right: string;
  }
}

declare const StylesExportModuleScssModule: StylesExportModuleScssNamespace.IStylesExportModuleScss;

export = StylesExportModuleScssModule;
