// AUTOGENERATED FILE -- DO NOT EDIT DIRECTLY
declare namespace StylesModuleScssNamespace {
  export interface IStylesModuleScss {
    left: string;
    logo: string;
    mobileMenuButton: string;
    mobileNavbarIcons: string;
    navItem: string;
    navbar: string;
    right: string;
    row: string;
  }
}

declare const StylesModuleScssModule: StylesModuleScssNamespace.IStylesModuleScss;

export = StylesModuleScssModule;
