// AUTOGENERATED FILE -- DO NOT EDIT DIRECTLY
declare namespace StylesExportModuleScssNamespace {
  export interface IStylesExportModuleScss {
    anchor: string;
    heading: string;
    linkIconSize: string;
    path: string;
    svg: string;
  }
}

declare const StylesExportModuleScssModule: StylesExportModuleScssNamespace.IStylesExportModuleScss;

export = StylesExportModuleScssModule;
