// AUTOGENERATED FILE -- DO NOT EDIT DIRECTLY

declare namespace StylesModuleScssNamespace {
  export interface IStylesModuleScss {
    card: string;
    description: string;
    grid: string;
    title: string;
    truncate: string;
  }
}

declare const StylesModuleScssModule: StylesModuleScssNamespace.IStylesModuleScss;

export = StylesModuleScssModule;
