// AUTOGENERATED FILE -- DO NOT EDIT DIRECTLY
declare namespace StylesModuleScssNamespace {
  export interface IStylesModuleScss {
    backdrop: string;
    backdropVisible: string;
    drawer: string;
    pane: string;
    panes: string;
    show: string;
    showSecondaryPane: string;
    switchPaneButton: string;
  }
}

declare const StylesModuleScssModule: StylesModuleScssNamespace.IStylesModuleScss;

export = StylesModuleScssModule;
