// AUTOGENERATED FILE -- DO NOT EDIT DIRECTLY
declare namespace ExportsModuleScssNamespace {
  export interface IExportsModuleScss {
    cssVarPrismBackgroundColor: string;
    cssVarPrismColor: string;
  }
}

declare const ExportsModuleScssModule: ExportsModuleScssNamespace.IExportsModuleScss;

export = ExportsModuleScssModule;
