// AUTOGENERATED FILE -- DO NOT EDIT DIRECTLY

declare namespace StylesExportModuleScssNamespace {
  export interface IStylesExportModuleScss {
    codeBlock: string;
    codeBlockContainer: string;
    content: string;
    copied: string;
    copyButton: string;
    copyIcon: string;
    icons: string;
    line: string;
    lineContent: string;
    lineNumber: string;
    lines: string;
    numbered: string;
    prismBackgroundColor: string;
    prismColor: string;
    standalone: string;
    successIcon: string;
    title: string;
  }
}

declare const StylesExportModuleScssModule: StylesExportModuleScssNamespace.IStylesExportModuleScss;

export = StylesExportModuleScssModule;
